server:
  port: 8080
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: bestuser
    password: bestuser
